name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Build Bcore AAR
        run: ./gradlew :Bcore:assembleRelease

      - name: Build Bcore Debug AAR
        run: ./gradlew :Bcore:assembleDebug

      - name: Find Bcore AAR paths
        id: aar_paths
        run: |
          DEBUG_AAR=$(find ./Bcore/build/outputs/aar -name "*debug.aar" | head -n 1)
          RELEASE_AAR=$(find ./Bcore/build/outputs/aar -name "*release.aar" | head -n 1)
          echo "debug_aar_path=$DEBUG_AAR" >> $GITHUB_OUTPUT
          echo "release_aar_path=$RELEASE_AAR" >> $GITHUB_OUTPUT

      - name: Find APK paths
        id: apk_paths
        run: |
          DEBUG_APK=$(find ./app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          RELEASE_APK=$(find ./app/build/outputs/apk/release -name "*.apk" | head -n 1)
          echo "debug_apk_path=$DEBUG_APK" >> $GITHUB_OUTPUT
          echo "release_apk_path=$RELEASE_APK" >> $GITHUB_OUTPUT
          
      - name: Upload Debug APKs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: ./app/build/outputs/apk/debug/*.apk
          retention-days: 30

      - name: Upload Release APKs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: ./app/build/outputs/apk/release/*.apk
          retention-days: 30

      - name: Upload Debug AARs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-aars
          path: ./Bcore/build/outputs/aar/*debug.aar
          retention-days: 30

      - name: Upload Release AARs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-aars
          path: ./Bcore/build/outputs/aar/*release.aar
          retention-days: 30

